version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
      include:
        - "*"
      exclude:
        - "ansys-sphinx-theme"
        - "ansys-tools-visualization-interface"
    labels:
      - "maintenance"
      - "dependencies"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "build"
    groups:
      grpc-deps:
        patterns:
          - "grpc*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
      include:
        - "*"
      exclude:
        - "ansys/actions/*"
    labels:
      - "maintenance"
      - "dependencies"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "ci"
